import type { Participant } from "@/lib/config";
export const demoRows: Participant[] = [
  {
    id: "1",
    name: "Marina Exemplo",
    company: "Empresa Exemplo",
    job_title: "Diretora",
    email: "marina@example.com",
    phone: "ex: 999999999",
    marketing: true,
    status: "complete",
    outcome: "cup",
    claim_code: "DEMO-7F3A92",
    redeemed_at: null,
  },
  {
    id: "2",
    name: "Lucas Demonstração",
    company: "Negócio Exemplo",
    job_title: "Gestor",
    email: "lucas@example.com",
    phone: "85989255170",
    marketing: false,
    status: "complete",
    outcome: "pen",
    claim_code: "DEMO-19AC43",
    redeemed_at: null,
  },
  {
    id: "3",
    name: "Ana Teste",
    company: "Empresa Modelo",
    job_title: "Fundadora",
    email: "ana@example.com",
    phone: "85989255170",
    marketing: true,
    status: "complete",
    outcome: "keychain",
    claim_code: "DEMO-82BB71",
    redeemed_at: "2026-10-07T12:00:00Z",
  },
];
